#! /bin/sh

DISTROOT=/space/downloads
MOUNTROOT=/space/install
EXPORT=192.168.178.0/24
SERVER=$(hostname)

#set -x

error()
{
   msg=$1
   echo -e "$msg" >&2
   exit 1
}

[ "$(id -u)" != "0" ] && error "$0 must be run as root."
[ -z "$SERVER" ] && error "Cannot determine server."

ip=$(host $SERVER)
ip=${ip##* }

[ -z "$ip" ] && error "Cannot look up ip."

for i in $MOUNTROOT/*
do
  [ ! -d $i ] && continue
  [ ! -e $i/suse -a ! -e $i/media.1 ] && continue
  dir=$(basename $i)
  if [ ! -e $DISTROOT/$dir.iso ]
  then
     mount | grep -q $dir && 
     { exportfs -u $EXPORT:/$i; umount $i; }
     rm -rf $i
  fi
done

for i in $DISTROOT/*.iso
do
   i=$(basename $i)
   file=${i%.iso}
   [ -d $MOUNTROOT/$file ] || mkdir $MOUNTROOT/$file || error "Can't mkdir $MOUNTROOT/$file"
   [ -d $MOUNTROOT/$file/suse -o -d $MOUNTROOT/$file/media.1 ] || mount -o loop $DISTROOT/$i $MOUNTROOT/$file || error "Can't mount $i"
   exportfs  $EXPORT:$MOUNTROOT/$file || error "Can't export $i"
done

slplist="$(slptool findsrvs install.suse)"

for i in $slplist 
do
   echo $i | grep -q $SERVER || continue
   url=${path%,*}
   path=$(echo $url | cut -f 4)
   path=$(echo path | sed "s#//[^/]\+/##")
   -d $path || slptool deregister $url
done

for i in $MOUNTROOT/*
do
  [ ! -e $i/suse -a ! -e $i/media.1 ] && continue

   for j in $slplist
   do
        echo $j | grep nfs | grep -q $i && continue 2
   done
   echo nfs $i
   slptool register service:install.suse:nfs://${ip}${i} || error "Cannot register $i"
done
for i in $MOUNTROOT/*
do
  [ ! -e $i/suse -a ! -e $i/media.1 ] && continue

   for j in $slplist
   do
        echo $j | grep ftp | grep -q $i && continue 2
   done
   i=${i##$MOUNTROOT}
   echo ftp $i
   slptool register service:install.suse:ftp://${ip}${i} || error "Cannot register $i"
done
