#!/bin/sh
#set -x

DELIMITER=_
optlist=
optlist_tail=
project=
checkout=0
add_dir=0

IBS=https://api.suse.de
OBS=https://api.opensuse.org

if [ "$(basename $0)" = "iosc-wrapper" ]
then
    apiopt="-A $IBS"
else
    apiopt="-A $OBS"
fi

while [ -n "$1" ]
do
        package=
	case $1 in
	    -A)
		optlist="$optlist $1 $2"
		apiopt=
		shift; shift
		;;
	    -c)
		optlist="$optlist $1 $2"
		shift; shift
		;;
	    -*)
		optlist="$optlist $1"
		shift
		;;
	    checkout|co)
		checkout=1
		[ ! -d ./.osc -o ! -e ./.osc/_project ] && add_dir=1
		optlist="$optlist $1"
		shift
		break
		;;
	    *)
		break
		;;
	esac
done

optlist="$apiopt $optlist"

if [ $checkout -eq 1 ]
then
    while [ -n "$1" ]
    do
	package=
	case $i in
	    -o)
		add_dir=0
		optlist_tail="$optlist_tail $1 $2"
		shift; shift
		;;
	    --output-dir*)
		add_dir=0
		optlist_tail="$optlist_tail $1"
		shift;
		;;
	    -l|-r)
		optlist_tail="$optlist_tail $1 $2"
		shift; shift
		;;
	    -*)
		optlist_tail="$optlist_tail $1"
		shift;
		;;
	    *)
		if [ -z $project ]
		then
		    project="$1"
		    if [[ "$pro" =~ "/" ]]
		    then
			package=${project##*/}
			project=${project%%/*}
		    fi
		    [[ $project =~ ":" ]] || add_dir=0
		else
		    package="$1"
		fi
		optlist_tail="$optlist_tail $1"
		shift;
		;;
	esac
    done
else
    optlist="$optlist $@" 
fi

if [ -n "$project" -a -z "$package" ] && \
    [[ "$project" =~ .+/.*+ ]]
then
    package=${project##*/}
    project=${project%/*}
fi

#if [ $add_dir -eq 1 ]
#then
#    if [ -n "$package" ] 
#    then
#	add_arg="-o $dir"
#    else
#	add_arg="-c $dir"
#    fi
#fi

optlist="$optlist $add_arg $optlist_tail"
echo $optlist

restore () {
    local unpacktmp project
    unpacktmp=$1
    project=$2
    [ -n "$unpacktmp" -a -d "$unpacktmp" ] && { mv $unpacktmp/$project . ; rmdir $unpacktmp; }
}

if [ $add_dir -ne 1 ]
then
    exec /usr/bin/osc $optlist
else
    dir=${project//:/$DELIMITER}  # ${package:+/}$package
    # Move $project out of the way if it exists
    if [ -d ${project} ]
    then
	unpacktmp=$(mktemp -d "tmp-XXXXXXX") || exit 1
	mv $project $unpacktmp || { rmdir $unpacktmp; exit 1; }
    fi
    # if target directory exists, simply create a link
    [ -d $dir ] && { ln -s ${dir} ${project} || { restore $unpacktmp $project; exit 1; }; }
    /usr/bin/osc $optlist
    ret=$?
    if [ -d $dir ]
    then
	# remove link
	rm $project
    else
	# target directory didn't exist. Simply move $project directory on success
	if [ $ret -eq 0 ]; then mv $project ${dir}; else rm -rf $project; fi
    fi
    # Move $project back if it has existed
    restore $unpacktmp $project
    exit $ret
fi
