#!/bin/sh
#set -x
#SLDELAY=15
#WKDELAY=30
#SLEEP=hibernate
SLDELAY=8
WKDELAY=15
SLEEP=suspend
STMP=/tmp/$SLEEP-stmp

die()
{
	arg=$1
	echo -en "$arg \n" >&2
	exit 1
}

usage()
{
    echo -en "$(basename $0) [-h] [-s <sleep_delay>] [-w <wakeup_delay>]\n"
    echo -en "Options:\n"
    echo -en "\t-h: hibernate (default: suspend)\n"
    echo -en "\t-w <wakeup_delay>: set delay between suspend and wakeup (default 15 sec)\n"
    echo -en "\t-s <suspend_delay>: set delay before suspend (defaut 8 sec)\n"
    echo -en "\t-h: usage\n"
}
while test -n "$1"
do
    case "$1" in
	-H) shift; SLEEP=hibernate ;;
	-s) shift SLDELAY=$1; shift ;;
	-w) shift; WKDELAY=$i; shift ;;
	-h|-?|--help) usage; exit 0 ;;
	*) die "Unknown option" ;;
    esac
done

[ -z "$SDELAY" ] || [[ "$SDELAY" =~ ^-.* ]] && \
    die "no argument specified with -s option"
[ -n  "$WKDELAY" ]  || [[ "$WDELAY" =~ ^-.* ]] && \
    die "no argument specified with -w option"

test -r /sys/class/rtc/rtc0/since_epoch || die "cannot get time"
test -w /sys/class/rtc/rtc0/wakealarm || die "cannot set wakeup"

cnt=0
echo -en "$cnt \n" > $STMP
tmpfl=$(mktemp /dev/shm/$0-XXXXXXXX)
touch $tmpfl
echo $tmpfl
sleep=-u

if [ -x /usr/bin/systemctl ]
then
    sleepcmd="/usr/bin/systemctl $SLEEP"
else
    if [ "$SLEEP" = "hibernate" ]
    then
	sleepcmd="/usr/bin/powersave -U"
    else
	sleepcmd="/usr/bin/powersave -u"
    fi
fi

while true
do
	test -e $tmpfl || { echo -n "$SLEEP cycles:"; cat $STMP; exit 0; }
	cnt=$(( $cnt + 1 ))
	secs=$(cat /sys/class/rtc/rtc0/since_epoch)
	wkup=$(( $secs + $WKDELAY ))
	echo  0 > /sys/class/rtc/rtc0/wakealarm || die "Cannot reset wakeup"
	echo  $wkup > /sys/class/rtc/rtc0/wakealarm || die "Cannot set wakeup"
	sleep 1
	$sleepcmd
	echo -en "$cnt \n" > $STMP
	sleep $SLDELAY
done
